version: "3"

vars:
  BUILD_DIR: '{{default "ignore/build" .BUILD_DIR}}'
  CONFIG: '{{default "Release" .CONFIG}}'
  # For Windows MSVC generator:
  VS_GEN: 'Visual Studio 17 2022'
  VS_ARCH: 'x64'

tasks:

  default:
    desc: Build BespokeSynth (configure + compile)
    deps: [submodules]
    cmds:
      - task: configure
      - task: build

  submodules:
    desc: Init / update git submodules recursively
    cmds:
      - git submodule update --init --recursive

  # -------------------------------
  # Install: meta helpers
  # -------------------------------
  install:
    desc: Install build prerequisites (chooses a platform task)
    cmds:
      - task: install:windows
      - task: install:wsl
      - task: install:linux
      - task: install:mac
    silent: true

  install:windows:
    desc: Install tools on Windows (requires admin shell for winget/choco)
    platforms: [windows]
    cmds:
      - cmd: winget install -e --id Kitware.CMake
        ignore_error: true
      - cmd: winget install -e --id Git.Git
        ignore_error: true
      - cmd: winget install -e --id Python.Python.3.12
        ignore_error: true
      - echo Ensure VS 2022 with "Desktop development with C++" workload is installed.

  # WSL detection: run only if /proc/version mentions Microsoft or WSL env is present
  install:wsl:
    desc: Install deps for WSL (Ubuntu). Skips if not WSL.
    platforms: [linux]
    cmds:
      - sudo apt update
      - sudo apt install -y build-essential cmake ninja-build pkg-config git python3-dev python3-venv python3-pip
      - sudo apt install -y libasound2-dev libjack-jackd2-dev \
          libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxext-dev libxi-dev \
          libxcomposite-dev libxrender-dev libglu1-mesa-dev mesa-common-dev
      - sudo apt install -y libfreetype6-dev libcurl4-openssl-dev libgtk-3-dev libwebkit2gtk-4.1-dev
      - |
        if [ -f /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.1.pc ] && \
           [ ! -f /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.0.pc ]; then
          echo "Creating pkg-config alias for webkit2gtk-4.0 -> 4.1"
          sudo ln -s /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.1.pc \
                     /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.0.pc
        fi
      - 'echo "Note: WSL is OK for compiling, but audio/MIDI support is limited."'

  install:linux:
    desc: Install deps for native Linux (Ubuntu/Debian). Skips under WSL.
    platforms: [linux]
    status:
      - 'grep -qiE "(microsoft|wsl)" /proc/version && exit 1 || exit 0'
    cmds:
      - sudo apt update
      - sudo apt install -y build-essential cmake ninja-build pkg-config git python3-dev python3-venv python3-pip
      - sudo apt install -y libasound2-dev libjack-jackd2-dev \
          libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxext-dev libxi-dev \
          libxcomposite-dev libxrender-dev libglu1-mesa-dev mesa-common-dev
      - sudo apt install -y libfreetype6-dev libcurl4-openssl-dev libgtk-3-dev
      - |
        if apt-cache show libwebkit2gtk-4.1-dev >/dev/null 2>&1; then
          sudo apt install -y libwebkit2gtk-4.1-dev
          if [ -f /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.1.pc ] && \
             [ ! -f /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.0.pc ]; then
            sudo ln -s /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.1.pc \
                       /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.0.pc
          fi
        else
          # On some distros it may still be 4.0
          sudo apt install -y libwebkit2gtk-4.0-dev || true
        fi

  install:mac:
    desc: Install deps on macOS (Homebrew)
    platforms: [darwin]
    cmds:
      - xcode-select --install || true
      - brew update
      - brew install cmake pkg-config python freetype curl
      # JUCE uses native frameworks on macOS; GTK/WebKit not required here.

  # -------------------------------
  # Configure / Build
  # -------------------------------
  configure:
    desc: Configure CMake (platform-aware)
    deps: [submodules]
    cmds:
      - task: configure:windows
      - task: configure:posix
    silent: true

  configure:windows:
    desc: Configure for MSVC (Windows)
    platforms: [windows]
    cmds:
      - mkdir -Force "{{.BUILD_DIR}}" 2>$null || true
      - >
        cmake -S . -B "{{.BUILD_DIR}}"
        -G "{{.VS_GEN}}" -A "{{.VS_ARCH}}"
        -DCMAKE_BUILD_TYPE={{.CONFIG}}

  configure:posix:
    desc: Configure for POSIX (Linux/macOS/WSL)
    platforms: [linux, darwin]
    cmds:
      - mkdir -p "{{.BUILD_DIR}}"
      - cmake -S . -B "{{.BUILD_DIR}}" -DCMAKE_BUILD_TYPE={{.CONFIG}}

  build:
    desc: Compile BespokeSynth
    cmds:
      - task: build:windows
      - task: build:posix
    silent: true

  build:windows:
    desc: Build with MSVC
    platforms: [windows]
    cmds:
      - cmake --build "{{.BUILD_DIR}}" --config {{.CONFIG}} --parallel

  build:posix:
    desc: Build with Makefiles/Ninja on POSIX
    platforms: [linux, darwin]
    cmds:
      - cmake --build "{{.BUILD_DIR}}" --parallel

  clean:
    desc: Remove build directory
    cmds:
      - task: clean:windows
      - task: clean:posix
    silent: true

  clean:windows:
    platforms: [windows]
    cmds:
      - powershell -Command "Remove-Item -Recurse -Force '{{.BUILD_DIR}}' -ErrorAction SilentlyContinue"

  clean:posix:
    platforms: [linux, darwin]
    cmds:
      - rm -rf "{{.BUILD_DIR}}"

  # -------------------------------
  # Run helpers
  # -------------------------------
  run:
    desc: Run BespokeSynth (platform-aware)
    cmds:
      - task: run:windows
      - task: run:posix
    silent: true

  run:windows:
    platforms: [windows]
    cmds:
      - |
        .\\ignore\\build\\Source\\BespokeSynth_artefacts\\Release\\BespokeSynth.exe

  run:posix:
    platforms: [linux, darwin]
    cmds:
      - |
        BIN="{{.BUILD_DIR}}/Bespoke/BespokeSynth"
        [ -x "$BIN" ] || BIN="{{.BUILD_DIR}}/BespokeSynth"
        if [ -x "$BIN" ]; then
          "$BIN"
        else
          echo "Executable not found. Did the build succeed?"
          exit 1
        fi