//
// UDUI.RC2 - resources Microsoft Visual C++ does not edit directly
//

#ifdef APSTUDIO_INVOKED
//	#error this file is not editable by Microsoft Visual C++
#endif //APSTUDIO_INVOKED


// feb-2014: 
// When doing a 3DxWinCore release, it is only necessary to update the 3DXWINCORE_VERSION numbers
// The other derived files only need to be updated if they actually changed.  The MICRO build number
// used by MSI is now the revision number so we don't have to worry about incrementing it manually.
//
// Don't forget to update the Version.h and readme files.
//
// The installers' Version properties are also updated automatically.

// Current version
#define _3DXWINCORE_VERSION_MAJOR 17
#define _3DXWINCORE_VERSION_MINOR 2
#define _3DXWINCORE_VERSION_MICRO 6
#define _3DXWINCORE_VERSION_BUILD_NUMBER 15148
#define _3DXWINCORE_SVN_WCREV 11461

#define HIDDEV_VERSION_MAJOR 10
#define HIDDEV_VERSION_MINOR 1

#define S80TRANS_VERSION_MAJOR 3
#define S80TRANS_VERSION_MINOR 9

#define _3DXNLSERVERTRANS_VERSION_MAJOR 1
#define _3DXNLSERVERTRANS_VERSION_MINOR 0

#define MWMTRANS_VERSION_MAJOR 2
#define MWMTRANS_VERSION_MINOR 8

#define KMJTRANS_VERSION_MAJOR 3
#define KMJTRANS_VERSION_MINOR 1

#define JET_VERSION_MAJOR 1
#define JET_VERSION_MINOR 1

#define CUBE3D_VERSION_MAJOR 1
#define CUBE3D_VERSION_MINOR 1

#define CHICKEN_VERSION_MAJOR 1
#define CHICKEN_VERSION_MINOR 1

#define BICYCLEDI_VERSION_MAJOR 10
#define BICYCLEDI_VERSION_MINOR 1

#define PUZZLE_VERSION_MAJOR 2
#define PUZZLE_VERSION_MINOR 0

#define _3DXTEST_VERSION_MAJOR 1
#define _3DXTEST_VERSION_MINOR 0

#define MWMTEST_VERSION_MAJOR 1
#define MWMTEST_VERSION_MINOR 0

#define _3DXTSTMFC_VERSION_MAJOR 1
#define _3DXTSTMFC_VERSION_MINOR 1

#define CITYFLY_VERSION_MAJOR 1
#define CITYFLY_VERSION_MINOR 0

#define WIDGET_VERSION_MAJOR 1
#define WIDGET_VERSION_MINOR 0

#define LAUNCH3DXVIEWER_VERSION_MAJOR 1
#define LAUNCH3DXVIEWER_VERSION_MINOR 1

#define SIAPP_VERSION_MAJOR 4
#define SIAPP_VERSION_MINOR 2

#define SPWINI_VERSION_MAJOR 11
#define SPWINI_VERSION_MINOR 0

#define CATIADLL_VERSION_MAJOR 2
#define CATIADLL_VERSION_MINOR 0

#define MSOFFICEDLL_VERSION_MAJOR 1
#define MSOFFICEDLL_VERSION_MINOR 0

#define WIN32UTILSDLL_VERSION_MAJOR 1
#define WIN32UTILSDLL_VERSION_MINOR 0

#define MGL3DCTLRRPCSERVICE_VERSION_MAJOR 2
#define MGL3DCTLRRPCSERVICE_VERSION_MINOR 0



#define STRINGIZER(arg)       #arg
#define MACROSTRINGIZER(arg)  STRINGIZER(arg)


/////////////////////////////////////////////////////////////////////////////
// Add manually edited resources here...
#define IDR_LEGALCOPYRIGHT_ENUS "Copyright © 1998-2015 3Dconnexion.  All rights reserved."
#define IDR_LEGALCOPYRIGHT_DEDE "Copyright © 1998-2015 3Dconnexion.  Alle Rechte vorbehalten."
#define IDR_LEGALCOPYRIGHT_FRFR "Copyright © 1998-2015 3Dconnexion"
#define IDR_LEGALCOPYRIGHT_JPJP "Copyright © 1998-2015 3Dconnexion"
#define IDR_LEGALCOPYRIGHT_CHCH "Copyright © 1998-2015 3Dconnexion"

#define IDR_3DXWINCORE_PRODUCTVERSION_STR MACROSTRINGIZER(_3DXWINCORE_VERSION_MAJOR._3DXWINCORE_VERSION_MINOR._3DXWINCORE_VERSION_MICRO._3DXWINCORE_SVN_WCREV)
#define IDR_3DXWINCORE_PRODUCTVERSION_NUM _3DXWINCORE_VERSION_MAJOR,_3DXWINCORE_VERSION_MINOR,_3DXWINCORE_VERSION_MICRO,_3DXWINCORE_SVN_WCREV

#define IDR_3DXSERVICE_FILEVERSION_STR MACROSTRINGIZER(_3DXWINCORE_VERSION_MAJOR._3DXWINCORE_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_3DXSERVICE_FILEVERSION_NUM _3DXWINCORE_VERSION_MAJOR,_3DXWINCORE_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_3DXSERVICE_ENUS_FILEVERSION_STR MACROSTRINGIZER(_3DXWINCORE_VERSION_MAJOR._3DXWINCORE_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_3DXSERVICE_ENUS_FILEVERSION_NUM _3DXWINCORE_VERSION_MAJOR,_3DXWINCORE_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_3DXSERVICE_DEDE_FILEVERSION_STR MACROSTRINGIZER(_3DXWINCORE_VERSION_MAJOR._3DXWINCORE_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_3DXSERVICE_DEDE_FILEVERSION_NUM _3DXWINCORE_VERSION_MAJOR,_3DXWINCORE_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_3DXSERVICE_FRFR_FILEVERSION_STR MACROSTRINGIZER(_3DXWINCORE_VERSION_MAJOR._3DXWINCORE_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_3DXSERVICE_FRFR_FILEVERSION_NUM _3DXWINCORE_VERSION_MAJOR,_3DXWINCORE_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_3DXSERVICE_JPJP_FILEVERSION_STR MACROSTRINGIZER(_3DXWINCORE_VERSION_MAJOR._3DXWINCORE_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_3DXSERVICE_JPJP_FILEVERSION_NUM _3DXWINCORE_VERSION_MAJOR,_3DXWINCORE_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_3DXSERVICE_CHCH_FILEVERSION_STR MACROSTRINGIZER(_3DXWINCORE_VERSION_MAJOR._3DXWINCORE_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_3DXSERVICE_CHCH_FILEVERSION_NUM _3DXWINCORE_VERSION_MAJOR,_3DXWINCORE_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

// Used by SetAssemblyVersion.exe, which changes AssemblyInfo.cs.
// Note that this uses .'s not ,'s
/////  ** not used now.  Using autoincrementing.  Don't care that much about the actual value; just that it gets incremented.
//#define IDR_3DXHOME_FILEVERSION_STR 1.0.4.0

// Used by SetAssemblyInfo.exe.  Which changes AssemblyInfo.cs.
/////  ** not used now.  Using autoincrementing.  Don't care that much about the actual value; just that it gets incremented.
//#define IDR_3DXCONFIG_FILEVERSION_STR 1.0.20.0


#define IDR_HIDDEV_FILEVERSION_STR MACROSTRINGIZER(HIDDEV_VERSION_MAJOR.HIDDEV_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_HIDDEV_FILEVERSION_NUM HIDDEV_VERSION_MAJOR,HIDDEV_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_S80TRANS_FILEVERSION_STR MACROSTRINGIZER(S80TRANS_VERSION_MAJOR.S80TRANS_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_S80TRANS_FILEVERSION_NUM S80TRANS_VERSION_MAJOR,S80TRANS_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_3DXNLSERVERTRANS_FILEVERSION_STR MACROSTRINGIZER(_3DXNLSERVERTRANS_VERSION_MAJOR._3DXNLSERVERTRANS_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_3DXNLSERVERTRANS_FILEVERSION_NUM _3DXNLSERVERTRANS_VERSION_MAJOR,_3DXNLSERVERTRANS_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_MWMTRANS_FILEVERSION_STR MACROSTRINGIZER(MWMTRANS_VERSION_MAJOR.MWMTRANS_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_MWMTRANS_FILEVERSION_NUM MWMTRANS_VERSION_MAJOR,MWMTRANS_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_KMJTRANS_FILEVERSION_STR MACROSTRINGIZER(KMJTRANS_VERSION_MAJOR.KMJTRANS_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_KMJTRANS_FILEVERSION_NUM KMJTRANS_VERSION_MAJOR,KMJTRANS_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_JET_FILEVERSION_STR MACROSTRINGIZER(JET_VERSION_MAJOR.JET_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_JET_FILEVERSION_NUM JET_VERSION_MAJOR,JET_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_CUBE3D_FILEVERSION_STR MACROSTRINGIZER(CUBE3D_VERSION_MAJOR.CUBE3D_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_CUBE3D_FILEVERSION_NUM CUBE3D_VERSION_MAJOR,CUBE3D_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_CHICKEN_FILEVERSION_STR MACROSTRINGIZER(CHICKEN_VERSION_MAJOR.CHICKEN_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_CHICKEN_FILEVERSION_NUM CHICKEN_VERSION_MAJOR,CHICKEN_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_BICYCLEDI_FILEVERSION_STR MACROSTRINGIZER(BICYCLEDI_VERSION_MAJOR.BICYCLEDI_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_BICYCLEDI_FILEVERSION_NUM BICYCLEDI_VERSION_MAJOR,BICYCLEDI_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_PUZZLE_FILEVERSION_STR MACROSTRINGIZER(PUZZLE_VERSION_MAJOR.PUZZLE_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_PUZZLE_FILEVERSION_NUM PUZZLE_VERSION_MAJOR,PUZZLE_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_3DXTEST_FILEVERSION_STR MACROSTRINGIZER(_3DXTEST_VERSION_MAJOR._3DXTEST_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_3DXTEST_FILEVERSION_NUM _3DXTEST_VERSION_MAJOR,_3DXTEST_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_MWMTEST_FILEVERSION_STR MACROSTRINGIZER(MWMTEST_VERSION_MAJOR.MWMTEST_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_MWMTEST_FILEVERSION_NUM MWMTEST_VERSION_MAJOR,MWMTEST_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_3DXTSTMFC_FILEVERSION_STR MACROSTRINGIZER(_3DXTSTMFC_VERSION_MAJOR._3DXTSTMFC_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_3DXTSTMFC_FILEVERSION_NUM _3DXTSTMFC_VERSION_MAJOR,_3DXTSTMFC_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_CITYFLY_FILEVERSION_STR MACROSTRINGIZER(CITYFLY_VERSION_MAJOR.CITYFLY_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_CITYFLY_FILEVERSION_NUM CITYFLY_VERSION_MAJOR,CITYFLY_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_WIDGET_FILEVERSION_STR MACROSTRINGIZER(WIDGET_VERSION_MAJOR.WIDGET_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_WIDGET_FILEVERSION_NUM WIDGET_VERSION_MAJOR,WIDGET_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_LAUNCH3DXVIEWER_FILEVERSION_STR MACROSTRINGIZER(LAUNCH3DXVIEWER_VERSION_MAJOR.LAUNCH3DXVIEWER_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_LAUNCH3DXVIEWER_FILEVERSION_NUM LAUNCH3DXVIEWER_VERSION_MAJOR,LAUNCH3DXVIEWER_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_SIAPP_FILEVERSION_STR MACROSTRINGIZER(SIAPP_VERSION_MAJOR.SIAPP_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_SIAPP_FILEVERSION_NUM SIAPP_VERSION_MAJOR,SIAPP_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_SPWINI_FILEVERSION_STR MACROSTRINGIZER(SPWINI_VERSION_MAJOR.SPWINI_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_SPWINI_FILEVERSION_NUM SPWINI_VERSION_MAJOR,SPWINI_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_CATIADLL_FILEVERSION_STR MACROSTRINGIZER(CATIADLL_VERSION_MAJOR.CATIADLL_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_CATIADLL_FILEVERSION_NUM CATIADLL_VERSION_MAJOR,CATIADLL_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_MSOFFICEDLL_FILEVERSION_STR MACROSTRINGIZER(MSOFFICEDLL_VERSION_MAJOR.MSOFFICEDLL_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_MSOFFICEDLL_FILEVERSION_NUM MSOFFICEDLL_VERSION_MAJOR,MSOFFICEDLL_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_WIN32UTILSDLL_FILEVERSION_STR MACROSTRINGIZER(WIN32UTILSDLL_VERSION_MAJOR.WIN32UTILSDLL_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_WIN32UTILSDLL_FILEVERSION_NUM WIN32UTILSDLL_VERSION_MAJOR,WIN32UTILSDLL_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

#define IDR_MGL3DCTLRRPCSERVICE_FILEVERSION_STR MACROSTRINGIZER(MGL3DCTLRRPCSERVICE_VERSION_MAJOR.MGL3DCTLRRPCSERVICE_VERSION_MINOR._3DXWINCORE_VERSION_BUILD_NUMBER._3DXWINCORE_SVN_WCREV)
#define IDR_MGL3DCTLRRPCSERVICE_FILEVERSION_NUM MGL3DCTLRRPCSERVICE_VERSION_MAJOR,MGL3DCTLRRPCSERVICE_VERSION_MINOR,_3DXWINCORE_VERSION_BUILD_NUMBER,_3DXWINCORE_SVN_WCREV

/////////////////////////////////////////////////////////////////////////////
